on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Go 1.15.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: build
      run: |
        go test -cover ./... -v  -run=^Test

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
